# Welcome to Jekyll!
#

# Site settings
title: Corvallis Coffee Outside
description: |
  Coffee outside with
  or without bikes
  because why not?
owner: Corvallis Bicycle Collective # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: sylvan@corvallisbikes.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://corvalliscoffeeoutsi.de/" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/corvallis-coffee-outside
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/CorvallisBikes/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/corvallisbikes/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
